Login and Register tests
eduardPinter1/demoqaPlaywright pull request #1
Opened 2024-01-15 14:34 UTC by eduardPinter1

2024-01-15 14:37 UTC, FilipNedovic commented on fixtures/ApiUrl.json
> +    "books": "https://demoqa.com/BookStore/v1/Books"
Pre bih ove endpoint-e organizovao unutar env u config fajlu.

2024-01-15 14:39 UTC, FilipNedovic commented on fixtures/userData.json
> +        "usernamePresent": "User exists!"
Dodaj samo _Message_ na kraju da bi bilo jasnije šta property sadrži kada ga koristiš u testu.

2024-01-15 14:39 UTC, FilipNedovic commented on fixtures/userData.json
> +        "result": "User authorization failed."
Isti komentar kao gore.

2024-01-15 14:42 UTC, FilipNedovic commented on tests/API/LoginAPI.spec.js
> +
Ovo bih izvukao kao posebnu varijablu pa bih prosleđivao kao `data: credentials/userPayload` ili tako nešto.

2024-01-15 14:43 UTC, FilipNedovic commented on tests/API/LoginAPI.spec.js
> +   console.log(regResponseJson);
Console log-ovi se u 99% slučajeva ne dižu na git (sem ako nemaš bas neki sistem logovanja ili reporter koji zavisi od njih).

2024-01-15 14:45 UTC, FilipNedovic commented on tests/API/LoginAPI.spec.js
> +})
Ostavljaj jednu praznu liniju na kraju svakog fajla, čisto neka JS konvencija.

2024-01-15 14:46 UTC, FilipNedovic commented on tests/API/LoginAPI.spec.js
> +           "userName" : userData.login.username+"e",
Drugi način da konkateniraš string: `${userData.login.username}e`

2024-01-15 14:51 UTC, FilipNedovic commented on tests/API/LoginAPI.spec.js
> +   expect(registrationResponse.status()).toBe(200);
I status kode bih izmestio odavde, da li kao JSON ili u JS fajl, ovako nekako:
```export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  NOT_FOUND: 404,
  SERVER_ERROR: 500
}

expect(registrationResponse.status()).toBe(STATUS_CODES.OK)```

2024-01-15 14:56 UTC, FilipNedovic reviewed
Izmesti API metode u posebnu klasu (`APIUtils` npr.)

2024-01-15 14:57 UTC, FilipNedovic commented on tests/API/RegisterApi.spec.js
> +    const randomNum = faker.number.bigInt(1000);
Nisi morao da koristiš faker, probaj s ugrađenim JS funkcijama.

2024-01-15 14:59 UTC, FilipNedovic commented on tests/API/RegisterApi.spec.js
> +    const responseBody = JSON.parse(await registrationResponse.text());
Na više mesta parsiraš text response-a, kandidat za util funkciju.

2024-01-16 10:57 UTC, FilipNedovic commented on tests/API/LoginAPI.spec.js
> +const credEmptyUsername = {
Izbriši konstantu ako je ne koristiš

2024-01-16 10:59 UTC, FilipNedovic commented on utils/ApiUtils.js
> +         if(emptyFields === true){
Probaj sa ternarnim operatorom

2024-01-16 11:00 UTC, FilipNedovic commented on utils/ApiUtils.js
> +    async nonValidLogin(credentials, statusCode, emptyFields, errorMessage){
Dodaj default-nu vrednost ulaznog parametra - `emptyFields = true`.

2024-01-16 11:04 UTC, FilipNedovic commented on tests/API/RegisterApi.spec.js
> +    console.log(userCred);
Briši console.log

2024-01-16 11:16 UTC, FilipNedovic approved these changes

2024-01-16 11:42 UTC, andrija989 requested changes
Svaka grupa API mora da ima svoju klasu

2024-01-17 12:13 UTC, merged